apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
type: Opaque
data:
  {{- range $k, $v := .Values.secrets }}
  {{$k}}: {{$v | b64enc}}
  {{- end}}